### PR TITLE
Require libbpf 1.5.0

### PR DESCRIPTION
**Pull request by viktormalik**
libbpf 1.5.0 has been released [1] and it contains support for "module:function" syntax for fentry/fexit probes which is required by bpftrace.

Update libbpf requirement in CMakeLists.txt and Nix flake to 1.5.0.

[1] https://github.com/libbpf/libbpf/releases/tag/v1.5.0

##### Checklist

- [ ] Language changes are updated in `man/adoc/bpftrace.adoc`
- [ ] User-visible and non-trivial changes updated in `CHANGELOG.md`
- [ ] The new behaviour is covered by tests

### CODE REVIEW

**Comment by viktormalik** [comment]
Static build is failing b/c alpine has old libbpf. They have libbpf 1.5.0 in the [edge branch](https://pkgs.alpinelinux.org/packages?name=libbpf&branch=edge&repo=&arch=x86_64&origin=&flagged=&maintainer=) and they should release new version 3.21 some time in November.

**Comment by viktormalik** [comment]
Same applies to distro builds which will all fail ATM.

**Comment by viktormalik** [comment]
> Same applies to distro builds which will all fail ATM.

Distro builds now pass as devel Debian, Ubuntu, and Fedora all have libbpf 1.5.

**Review by ajor — APPROVED** [review]

**Review by danobi — APPROVED** [review]

**Comment by viktormalik** [comment]
The static build failure should be addressed by #3631.

**Comment by viktormalik** [comment]
And now we have all the CI jobs passing :partying_face:

**Pull request merged**
