### PR TITLE
Fix paths: iovisor/bpftrace -> bpftrace/bpftrace

### PR DESCRIPTION
**Pull request by jordalgo**
After moving to the new bpftrace org, update these paths.

##### Checklist

- [ ] Language changes are updated in `man/adoc/bpftrace.adoc` and if needed in `docs/reference_guide.md`
- [ ] User-visible and non-trivial changes updated in `CHANGELOG.md`
- [ ] The new behaviour is covered by tests

### CODE REVIEW

**Comment by jordalgo** [comment]
I updated the changelog too (not sure if I should have left that one alone)

**Review by danobi — APPROVED** [review]
I assume it was a pretty mechanical `sed` so I did not look super closely

**Review by viktormalik — COMMENTED** [review]
Found a couple more usages:
- src/utils.cpp:1285
- docs/internals_development.md (multiple places)

**Comment by jordalgo** [comment]
> src/utils.cpp:1285

Good catch. I forgot about iovisor:bpftrace.

> docs/internals_development.md (multiple places)

I only see iovisor in the context of bcc, which shouldn't change. Am I missing something?

**Review by viktormalik — APPROVED** [review]
Thanks!

**Pull request merged**
