### PR TITLE
Fix min/max map functions

### PR DESCRIPTION
**Pull request by jordalgo**
Since these work off of per-cpu maps, it means that when a key is added the value for the key across all cpus initializes to 0. Therefore if we loop over all cpus to determine if a value is greater or less than another we need to discount all 0 values that weren't set explicitly by the user/prog (e.g. min(0)).

To do this we need to keep a separate key (similar to `avg`) that acts like a "value was set" boolean so we know if we should consider it in a less-than or greater-than operation.

This needs to be done in both userspace (for map printing) and in kernel space for min/max implicit casting.

Issue: https://github.com/bpftrace/bpftrace/issues/3286

##### Checklist

- [ ] Language changes are updated in `man/adoc/bpftrace.adoc`
- [ ] User-visible and non-trivial changes updated in `CHANGELOG.md`
- [ ] The new behaviour is covered by tests

### CODE REVIEW

**Comment by jordalgo** [comment]
This is ugly but correct. The alternative is to have min/max use hash maps and an atomic min/max write after lookup - I don't know what would be faster but I'll try to run some tests to find out.

**Comment by ajor** [comment]
I don't understand the exact problem here as I can't trigger any wrong results except by using tuples. Left a comment on the issue (#3286).

**Comment by jordalgo** [comment]
Responded in the issue with a more detailed repro. 

Here is the alternative solution where we just convert min/max to use a hash map, which I'm leaning towards because it's just so much simpler AND preserves the ability to loop over min/max maps. https://github.com/bpftrace/bpftrace/pull/3290

**Comment by jordalgo** [comment]
Abandoning in favor of https://github.com/bpftrace/bpftrace/pull/3298, which stores a struct as the min/max map values instead of using two separate keys.

**Pull request closed without merging**
