### PR TITLE
Bump C++ standard to C++20

### PR DESCRIPTION
**Pull request by ajor**
##### Checklist

- [ ] Language changes are updated in `man/adoc/bpftrace.adoc`
- [ ] User-visible and non-trivial changes updated in `CHANGELOG.md`
- [ ] The new behaviour is covered by tests

### CODE REVIEW

**Comment by ajor** [comment]
It turns out that LLVM 12 is not compatible with C++20. Maybe it's time to drop support for LLVM 12?

**Comment by jordalgo** [comment]
I'm fine to move to llvm-13 as the min but there are other things that might need to be updated e.g. the codegen script. I'm also not sure of the implications on the distro side.

**Comment by viktormalik** [comment]
> I'm also not sure of the implications on the distro side.

There are LTS distros which have older LLVM (e.g. Ubuntu 20.04 with LLVM 10) but I think that they generally do not update bpftrace either. So, I *think* that we should be fine here but not 100% sure.

Codegen tests are currently on LLVM 12 so they would need to be migrated. Preferably to the latest (LLVM 18) but we'd lose codegen tests for typed (non-opaque) pointers, then.

**Comment by ajor** [comment]
I'm going to update the codegen tests in #3303

**Comment by ajor** [comment]
LLVM 12 has been removed as of #3325 and we're ready for C++20!

**Review by jordalgo — APPROVED** [review]
:rocket:

**Pull request merged**
