### PR TITLE
AST: Finish the refactoring of Lists from pointers to inline members

### PR DESCRIPTION
**Pull request by ajor**
Follow up to #3350

```
1. Remove the pointer-to-vector members
2. Rename the inline vector members to the pointers' old names
3. Update users of the AST to handle std::vector instead of pointers
  - This is mainly just replacing "->" with "."
  - The bigger changes come in places where we used to check for null
    pointers. Empty vectors are now used in place of null pointers, so
    these checks are not necessary before loops.
```

### CODE REVIEW

**Comment by ajor** [comment]
Just one more PR to come after this one (replacing pointers which can never be null with references (or equivalents)

**Review by jordalgo — APPROVED** [review]
Did a surface glance. Mostly relying on our tests for this one.

**Review by danobi — APPROVED** [review]

**Comment by jordalgo** [comment]
@ajor No rush or presh but when you fix the merge conflict and merge this, I can put up the PR for the lexical scope fix.

**Comment by ajor** [comment]
Go go go! :D

**Pull request merged**
