### PR TITLE
Doc: Access member variables correctly

### PR DESCRIPTION
**Pull request by YeechouTang**
Now, member variables should be accessed using '->' instead of '.'.

Both the original document and the Chinese translation have this issue, but the Japanese translation does not.

### CODE REVIEW

**Comment by YeechouTang** [comment]
> It's actually the other way around. Since #2578 (bpftrace 0.19), the recommended way to access `args` fields is via the dot operator. Using the arrow works, too, for backwards compatibility.

I see. The version of bpftrace installed on my Ubuntu is 0.15, and it throws an error when using '.' to run examples. So, perhaps a better approach would be to clarify in the documentation from which version '.' can be used?

**Comment by viktormalik** [comment]
> > It's actually the other way around. Since #2578 (bpftrace 0.19), the recommended way to access `args` fields is via the dot operator. Using the arrow works, too, for backwards compatibility.
> 
> I see. The version of bpftrace installed on my Ubuntu is 0.15, and it throws an error when using '.' to run examples. So, perhaps a better approach would be to clarify in the documentation from which version '.' can be used?

We have a plan to provide "versioning" for the documentation so that it is possible to access documentation for older versions of bpftrace. That will, however, take time to implement so adding a note to the one-liners tutorial probably makes sense as many people seem to stumble on this.

In addition, I've opened #3123 which adds a warning to the PR template which should notify people to actually reproduce their change on the latest version of bpftrace.

**Comment by viktormalik** [comment]
Anyways, I'm closing this PR.

**Comment by viktormalik** [comment]
I opened #3124 which adds a note to the one-liners tutorial (English version only for now).

**Pull request closed without merging**
