### PR TITLE
Support building with LLVM 18

### PR DESCRIPTION
**Pull request by danobi**
Support building bpftrace against the recently released LLVM 18.

##### Checklist

- [ ] Language changes are updated in `man/adoc/bpftrace.adoc`
- [ ] User-visible and non-trivial changes updated in `CHANGELOG.md`
- [x] The new behaviour is covered by tests

### CODE REVIEW

**Review by viktormalik — APPROVED** [review]
I assume that LLVM 18 is not in nixpkgs, yet, so we should just merge this and add the CI job once it is available.

**Review by ajor — APPROVED** [review]

**Comment by kloczek** [comment]
Is it possible to backport this PR to release/0.20.x branch or release new version out of master? 🤔

**Comment by danobi** [comment]
Hi @kloczek , speaking for myself, I'd prefer not to yet. We don't have LLVM 18 running in CI yet. So consider llvm 18 support under development.

**Comment by kloczek** [comment]
Any update about LLVM 18.1.x supporting new version? 🤔

**Comment by danobi** [comment]
@kloczek almost! Nix is about to release 24.05 (https://github.com/NixOS/nixpkgs/issues/303285) which contains llvm 18 package

**Comment by danobi** [comment]
Quick update: nix 24.05 is out and llvm 18 is present. I'm having a bit of trouble getting the nix build to function. Currently stuck with this error:

```
$ ./result/bin/bpftrace
./result/bin/bpftrace: error while loading shared libraries: libicuuc.so.74: cannot open shared object file: No such file or directory
```

LD_DEBUG=all is quite helpful. Seems like this is related to the recent lldb dependency addition:

```
$ LD_DEBUG=all ./result/bin/bpftrace
[..]
   2726159:     file=libicuuc.so.74 [0];  needed by /nix/store/hcag2qn4njvps4wpy7fnjb20y80fynni-lldb-18.1.5-lib/lib/../../../../lib/libxml2.so.2 [0]
   2726159:     find library=libicuuc.so.74 [0]; searching
[..]
```

**Comment by jordalgo** [comment]
@tyroguru We're you seeing a similar issue in your VM?

**Comment by danobi** [comment]
Looks like master is broken atm too: https://github.com/NixOS/nixpkgs/issues/315214#issuecomment-2134307949

**Comment by tyroguru** [comment]
> @tyroguru We're you seeing a similar issue in your VM?

Yes, that was it. Well remembered!

**Pull request merged**
