### PR TITLE
Fix inconsistent lhist bucket labels

### PR DESCRIPTION
**Pull request by ajor**
The 'K' and 'M' suffixes should either be applied to all buckets or to none. This can be achieved by only applying the suffixes if the step size is a multiple of 1024.

##### Checklist

- [ ] Language changes are updated in `man/adoc/bpftrace.adoc`
- [ ] User-visible and non-trivial changes updated in `CHANGELOG.md`
- [x] The new behaviour is covered by tests

### CODE REVIEW

**Review by danobi — COMMENTED** [review]
in theory we should be able to unit test everything in output.cpp, right?

**Comment by ajor** [comment]
> in theory we should be able to unit test everything in output.cpp, right?

Damn it, I wanted to be lazy! 😛

Yeah, you're right, that'd be a better approach. I'll try and update this PR to do that.

**Comment by ajor** [comment]
Updated to create and use unit tests instead of runtime tests. This now depends on #3086, so I've marked it as a draft until that gets merged.

**Review by danobi — APPROVED** [review]
lgtm. thanks for setting up the unit tests! next one will be much easier to add

**Pull request merged**
